server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql:///test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
      name: item-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka
    register-with-eureka: true
  instance:
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.leyou.item.pojo
#item-service:
#  ribbon:

  # spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule