server:
  port: 8088
spring:
  application:
    name: leyou-registry
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000

